import Footer from "@/components/footer";
import Header from "@/components/header";
import theme from "@/components/them";
import { Box, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import "./globals.css";
import StoreProvider from "./StoreProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="en">
      <body className="!bg-neutral-50">
        <StoreProvider>
          {/* The (AppRouterCacheProvider) component is responsible for collecting the CSS generated by MUI System on the server */}
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <Box
                sx={{
                  font: "font-iranSans-medium",
                  backgroundColor: "neutral.50",
                  display: "flex",
                  flexDirection: "column",
                  justifyContent: "space-between",
                  minHeight: "100dvh",
                }}
              >
                <Header />
                {children}
                <Footer />
              </Box>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
